### ISSUE TITLE
Troubles with Async-Socket library.

### ISSUE THREAD

**Issue by shurikrulik** [omaflak/Async-Socket#1]
Hello Omar !
I have some troubles when i try compile your library. First of all i facing with such error when i ' make ' . 

./lib/socketClient.cpp: In member function ‘bool SocketClient::send(std::string, std::string)’:
./lib/socketClient.cpp:83:31: error: call of overloaded ‘send(std::string&, <brace-enclosed initializer list>)’ is ambiguous
     return send(key, {message});
                               ^
I fixed this trouble by adding std::string type for {message} argument at 83 line like this:

return send(key, std::string{message});

But after starting  server and client i facing with Segmentation fault  error. That as i understand caused by send method.

server side debug listing:

sudo gdb ./server
GNU gdb (Raspbian 7.7.1+dfsg-5+rpi1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./server...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/src/mytests/async_socket/Async-Socket/server
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
server started. Listening on port 8888...
client connected !
[New Thread 0xb6cb6450 (LWP 4741)]

Program received signal SIGSEGV, Segmentation fault.
0x000142a4 in SocketClient::send(std::string, std::string) ()
(gdb)

client side debug listing:

sudo gdb ./client
GNU gdb (Raspbian 7.7.1+dfsg-5+rpi1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./client...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/src/mytests/async_socket/Async-Socket/client
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xb6cb6450 (LWP 4742)]
connected to server.
input: hi

Program received signal SIGSEGV, Segmentation fault.
0xb6f4ef78 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
(gdb)

Do you know what can be reasons of this problems   ?
Any way, thank you for everythink )

**Comment by omaraflak** [comment]
Hi @shurikrulik 
Thank you very much for taking the time to report such errors.
It looks like using brackets to make a vector is not well supported by some compilers. I just fixed it by replacing it by : 

```c++
std::vector<std::string> msg = {message};
return send(key, msg);
```

All you need is a ` git pull && make`  and you're ready to go ;)

**PS:** maybe I should emphasize that here the server is only forwarding the client messages. So you'll have to start at least two clients to see how this works.
